name: Create and publish an Apptainer image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Apptainer
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Setup apptainer executable
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0

      - name: Build an apptainer image
        run: apptainer build --build-arg PYBIOCLIP_VERSION=${{ steps.meta.outputs.version }} bioclip.sif apptainer.def

      - name: Publish apptainer image
        run: apptainer push bioclip.sif oras://ghcr.io/johnbradley/apptainer-test-sif:${{ steps.meta.outputs.version }}
