
name: Create and publish a Docker image

on:
  push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-apptainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup apptainer executable
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.3

      - name: Build an apptainer image
        run: apptainer build --build-arg PYBIOCLIP_VERSION=1.0.0 apptainer.sif apptainer.def

      - name: Publish apptainer image
        run: apptainer push apptainer.sif "oras://${{ env.REGISTRY }}/${IMAGE_NAME,,}-sif:1.0.1"
